layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 17
  exclude:
    archived: false
    forks: true
    projects:
      - francis94c.github.io
      - Travelmantics
      - sms-vote-web-app
      - agricultural-e-commerce
      - ALC40Phase1

products:
  - name: Splint
    url: https://splint.cynobit.com
    image: https://splint.cynobit.com/images/logo.png
    description: A Package and Dependency Manager for Code Igniter.
    languages:
      - php:
      - java:

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: francis94c
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  medium: francis94c
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: francis94c
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  youtube: francis94c

topics:
  - name: Code Igniter
    web_url: https://codeigniter.com
    image_url: https://cdn.worldvectorlogo.com/logos/codeigniter.svg

  - name: Android
    web_url: https://github.com/topics/android
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/android/android.png

  - name: FireBase
    web_url: https://firebase.google.com
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/firebase/firebase.png
    
  - name: PHP
    web_url: https://github.com/topics/php
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/php/php.png
    
  - name: Flutter
    web_url: https://flutter.dev
    image_url: https://raw.githubusercontent.com/github/explore/cebd63002168a05a6a642f309227eefeccd92950/topics/flutter/flutter.png
    
  - name: Python
    web_url: https://python.org
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png
  
  - name: Java
    web_url: https://github.com/topics/java
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/java/java.png
    
  - name: JavaFX
    web_url: https://github.com/topics/javafx
    image_url: https://raw.githubusercontent.com/github/explore/00edd8b9cf9eb98be328184dcc257f3b1b930c6b/topics/javafx/javafx.png
    
  - name: Splint
    web_url: https://splint.cynobit.com
    image_url: https://splint.cynobit.com/images/logo.png
    
  - name: Google Cloud Platform
    web_url: https://github.com/topics/gcp
    image_url: https://avatars1.githubusercontent.com/u/2810941?s=280&v=4
    
  - name: Arduino
    web_url: https://github.com/topics/arduino
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/arduino/arduino.png
  
  - name: MySQL
    web_url: https://github.com/topics/mysql
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/mysql/mysql.png
  
  - name: Node.JS
    web_url: https://github.com/topics/node
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/nodejs/nodejs.png
  
  - name: Vue
    web_url: https://github.com/topics/vue
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/vue/vue.png
